Feature 135 json list examples guidance
ESIPFed/science-on-schema.org pull request #187
Opened 2021-12-05 23:29 UTC by ashepherd

- [ ] Adds use of `@list` to full example.
- [ ] Omits `@list` example in the minimal JSON-LD example file becuase it's not required for all Datasets.
- [ ] Adds a block of text and code example to the Dataset guide displaying use of `@list` for the `creator` property and references the explanation of JSON-LD unordered lists in the GETTING-STARTED document.

2021-12-06 18:54 UTC, mbjones commented
@ashepherd Your PR for the element ordering with `@list` looks good, but I not there are a bunch of changes in the PR to the checksum feature (which was already merged to develop in https://github.com/ESIPFed/science-on-schema.org/pull/171), and to the funding feature (which was already merged to develop in https://github.com/ESIPFed/science-on-schema.org/pull/163). I'm unclear why your PR has these changes, and I would want to check to be sure nothing gets accidentally reverted. Is your PR up-to-date wrt `develop`? I can look in more detail later if needed.

2021-12-06 19:41 UTC, ashepherd commented
just set the merge from `master` to `develop`. that fixed it

2021-12-06 21:34 UTC, mbjones approved these changes

2021-12-06 21:34 UTC, mbjones commented
Thanks. LGTM.

2021-12-06 23:24 UTC, smrgeoinfo approved these changes

2021-12-07 02:15 UTC, datadavev requested changes
Couple of minor typos, but otherwise all good

2021-12-07 02:15 UTC, datadavev commented on guides/Dataset.md
> +NOTE: Becuase JSON-LD doesn't preserve the order of its collection values, for more see [Getting Started - JSON-LD Lists](GETTING-STARTED.md#json-ld-list), we can preserve the order of people roles b
Typo, "Because"

2021-12-07 02:15 UTC, datadavev commented on guides/Dataset.md
> +Becuase there are more things that can be said about how and when a person contributed to a Dataset, we use the [schema:Role](https://schema.org/Role). You'll notice that the schema.org documentation
typo, "Because ..."

2021-12-07 14:13 UTC, ashepherd commented
typos fixed!

2022-03-02 15:50 UTC, merged